import { useContext } from "react"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { Context } from "./_app"
// import theme from "../styles/theme"
import { themeLith, themeDark } from "../styles/theme"

export default function Home() {
  const { global } = useContext(Context)
  const theme = global.isLith ? themeLith : themeDark
  console.log("index.js/global=", global)
  console.log("index.js/theme=", theme)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to MOBX</h1>
        {/* <div style={{color: "red" }}>{global.isAuth?"1111":"2222"}</div> */}
        <div className="theme">{global.isAuth ? "1111" : "2222"}</div>
        {/* <div style={{ color: "${color1}" }}>{global.isAuth ? "1111" : "2222"}</div> */}
      </main>
      <style jsx>{`
        .theme {
          color: ${theme.colors.tableIcon};
        }
      `}</style>
    </div>
  )
}
